-- INSERT INTO Hotel VALUES (null , 'Addis Ababa', 'Desc about Sheraton', 'image','Sheraton')
-- INSERT INTO Hotel VALUES (null , 'Addis Ababa', 'Desc about Sheraton', 'image','Hilton')
-- INSERT INTO Hotel VALUES (null , 'Addis Ababa', 'Desc about Sheraton', 'image','Jupiter')
-- INSERT INTO Hotel VALUES (null , 'Addis Ababa', 'Desc about Sheraton', 'image','Radison Blue')
--
-- INSERT INTO Room VALUES (null , 2, 150.0, 101, 0,1);
-- INSERT INTO Room VALUES (null , 1, 85.0, 102, 0,1);
-- INSERT INTO Room VALUES (null , 1, 85.0, 103, 0,1);
-- INSERT INTO Room VALUES (null , 2, 150.0, 104, 0,1);
-- INSERT INTO Room VALUES (null , 1, 85.0, 105, 0,1);